/**
 * Defines the accepted layout sizing modifiers for a Blade Component.
 * These rigorously match the semantic widths generated by the core JSON orchestrator
 * or append additional local modifiers (like 'menu').
 */
export type BladeSize = 'menu' | 'small' | 'medium' | 'large' | 'xlarge' | 'xl' | '2xl' | '3xl' | '4xl' | '5xl' | '6xl' | '7xl' | 'full';

/**
 * A direct map resolving `BladeSize` literals into CSS Custom Property tailwind utility classes.
 * These target native CSS variables like `--sdui-blade-w-small` to allow 
 * consuming applications to dynamically re-theme the width geometries without SDK recompilation.
 */
export const bladeSizeClasses: Record<BladeSize, string> = {
    full: 'w-full flex-1 shrink',
    large: 'w-full max-w-[var(--sdui-blade-w-large,855px)] shrink',
    medium: 'w-full max-w-[var(--sdui-blade-w-medium,585px)] shrink',
    menu: 'w-full max-w-[var(--sdui-blade-w-menu,265px)] shrink',
    small: 'w-full max-w-[var(--sdui-blade-w-small,315px)] shrink',
    xlarge: 'w-full max-w-[var(--sdui-blade-w-xlarge,1125px)] shrink',
    xl: 'w-full max-w-[var(--sdui-blade-w-xl,1125px)] shrink',
    '2xl': 'w-full max-w-[var(--sdui-blade-w-2xl,1395px)] shrink',
    '3xl': 'w-full max-w-[var(--sdui-blade-w-3xl,1665px)] shrink',
    '4xl': 'w-full max-w-[var(--sdui-blade-w-4xl,1935px)] shrink',
    '5xl': 'w-full max-w-[var(--sdui-blade-w-5xl,2205px)] shrink',
    '6xl': 'w-full max-w-[var(--sdui-blade-w-6xl,2475px)] shrink',
    '7xl': 'w-full max-w-[var(--sdui-blade-w-7xl,2745px)] shrink',
};
